// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [{type: 'autogenerated', dirName: 'main'}],
  sidebar2: [{type: 'autogenerated', dirName: 'sidebar2'}],
  knowledgeBase: [{type: 'autogenerated', dirName: 'Knowledge Base'}],
};

module.exports = sidebars;
